# Generated by Django 4.2.2 on 2023-06-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20230611_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
